import React, { useState, useEffect, useCallback } from 'react';
import { Sidebar } from './components/Sidebar';
import { DataStudio } from './views/DataStudio';
import { Visualization } from './views/Visualization';
import { AiInsights } from './views/AiInsights';
import { Dashboard } from './views/Dashboard';
import { AuthView } from './components/AuthView';
import { SettingsModal } from './components/SettingsModal';
import { AppView, ChartConfig, ChatMessage, DashboardItem, User } from './types';

import { NotificationProvider, useNotification } from './contexts/NotificationContext';
import { DataProvider, useData } from './contexts/DataContext';
import { useSessionManager } from './hooks/useSessionManager';
import { apiClient } from './services/apiClient';

function AppContent() {
  const [currentView, setCurrentView] = useState<AppView>(AppView.DASHBOARD);
  const [activeFilters, setActiveFilters] = useState<Record<string, any[]>>({});
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  const { notify } = useNotification();
  const {
    data, headers, sessionId, dashboardItems,
    setData, setHeaders, setDashboardItems,
    uploadFile, loadSession, resetData
  } = useData();

  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    { id: '0', role: 'model', content: "Systems synchronized. Intelligence engine initialized. How shall we interrogate the data today?" }
  ]);

  const { deleteSession, renameSession } = useSessionManager(setChatMessages);

  const [user, setUser] = useState<User | null>(() => {
    const savedUser = localStorage.getItem('insightflow_user');
    return savedUser ? JSON.parse(savedUser) : null;
  });

  const [isDarkMode, setIsDarkMode] = useState(() => {
    const saved = localStorage.getItem('theme');
    return saved ? saved === 'dark' : true;
  });

  useEffect(() => {
    document.documentElement.classList.toggle('dark', isDarkMode);
    localStorage.setItem('theme', isDarkMode ? 'dark' : 'light');
  }, [isDarkMode]);

  const [vizConfig, setVizConfig] = useState<ChartConfig>({
    id: 'default', title: 'Intelligence Report', type: 'bar', xAxisKey: '', yAxisKeys: [],
    theme: 'default', aggregation: 'avg',
  });

  const handleLogin = (newUser: User) => {
    setUser(newUser);
    localStorage.setItem('insightflow_user', JSON.stringify(newUser));
  };

  const handleLogout = () => {
    setUser(null);
    localStorage.removeItem('insightflow_user');
    setCurrentView(AppView.DASHBOARD);
  };

  const handleLoadSession = async (sid: string) => {
    try {
      const sessionData = await loadSession(sid);
      if (sessionData.history) {
        setChatMessages(sessionData.history.map((msg: any, idx: number) => ({
          id: idx.toString(),
          role: msg.role === 'user' ? 'user' : 'model',
          content: msg.parts?.[0]?.text || ""
        })));
      }
      if (data?.length > 0) setCurrentView(AppView.INSIGHTS);
    } catch (e) {
      console.error("Load session failed:", e);
    }
  };

  const handleFileUpload = async (file: File) => {
    try {
      await uploadFile(file);
      setCurrentView(AppView.DATA);
    } catch (err) {
      console.error("Upload failed:", err);
    }
  };

  const handleAddToDashboard = useCallback((config: ChartConfig) => {
    setDashboardItems(prev => [...prev, {
      ...config, id: Date.now().toString(), x: 40, y: 40, width: 500, height: 400, zIndex: 10
    }]);
    notify('Insight Pinned to Workbench', 'success');
  }, [notify, setDashboardItems]);

  const handleProcessData = useCallback(async (action: string, payload: any) => {
    try {
      notify(`Processing: ${action}...`, 'info');
      const res = await apiClient.processData(sessionId, action, payload);
      if (res.status === 'success') {
        setData(res.sample || []);
        if (res.sample && res.sample.length > 0) {
          setHeaders(Object.keys(res.sample[0]));
        } else {
          setHeaders([]); // Clear headers if no data
        }
        notify("Processing complete. Updating view...", "success");
        return res;
      }
    } catch (e: any) {
      notify(`Processing failed: ${e.message}`, 'error');
      throw e; // Re-throw to allow caller to handle
    }
    return null;
  }, [sessionId, notify, setData, setHeaders]);

  const handleUndo = useCallback(async () => {
    try {
      const res = await apiClient.undo(sessionId);
      setData(res.sample || []);
      if (res.sample && res.sample.length > 0) {
        setHeaders(Object.keys(res.sample[0]));
      } else {
        setHeaders([]); // Clear headers if no data
      }
      notify(res.message || 'Action reverted', 'success');
    } catch (err: any) {
      notify(`Undo failed: ${err.message || 'Unknown error'}`, 'error');
    }
  }, [sessionId, notify, setData, setHeaders]);

  const handleAutoGenerateDashboard = useCallback(async () => {
    try {
      notify("Auto-generating dashboard...", "info");
      const result = await apiClient.generateDashboard(sessionId);
      if (result.charts) {
        const newItems = result.charts.map((c: any, i: number) => ({
          ...c, id: Date.now().toString() + i,
          x: (i % 2) * 520 + 40, y: Math.floor(i / 2) * 420 + 40,
          width: 500, height: 400, zIndex: 10
        }));
        setDashboardItems(prev => [...prev, ...newItems]);
        notify("Dashboard Generated!", "success");
      }
    } catch (e: any) {
      notify(`Generation failed: ${e.message}`, 'error');
    }
  }, [sessionId, notify, setDashboardItems]);

  if (!user) return <AuthView onLogin={handleLogin} isDarkMode={isDarkMode} onToggleTheme={() => setIsDarkMode(!isDarkMode)} />;

  return (
    <div className="flex h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 transition-colors duration-500">
      <Sidebar
        currentView={currentView} user={user} isOpen={isSidebarOpen} isDarkMode={isDarkMode}
        onToggleTheme={() => setIsDarkMode(!isDarkMode)} onToggle={() => setIsSidebarOpen(!isSidebarOpen)}
        onNavigate={setCurrentView} onOpenSettings={() => setIsSettingsOpen(true)} onLogout={handleLogout}
        onLoadSession={handleLoadSession} onRenameSession={renameSession} onDeleteSession={(id) => deleteSession(id, sessionId, resetData)}
      />
      <main className="flex-1 flex flex-col min-w-0 transition-all relative overflow-hidden">
        <div className="flex-1 overflow-hidden animate-fade-in relative">
          <div className={currentView === AppView.DASHBOARD ? 'h-full' : 'hidden h-full'} aria-hidden={currentView !== AppView.DASHBOARD}>
            <Dashboard
              data={data} isDarkMode={isDarkMode} headers={headers} items={dashboardItems}
              onUpdateItem={(id, updates) => setDashboardItems(prev => prev.map(item => item.id === id ? { ...item, ...updates } : item))}
              onRemoveItem={(id) => setDashboardItems(prev => prev.filter(item => item.id !== id))}
              onNavigateToData={() => setCurrentView(AppView.DATA)} onAutoGenerate={handleAutoGenerateDashboard}
              sessionId={sessionId} onAskAboutChart={(t) => {
                setChatMessages(prev => [...prev, { id: Date.now().toString(), role: 'user', content: `Explain trends in "${t}"` }]);
                setCurrentView(AppView.INSIGHTS);
              }}
              onUndo={() => notify("Undo not implemented for workbench layout yet", "info")}
            />
          </div>
          <div className={currentView === AppView.DATA ? 'h-full' : 'hidden h-full'} aria-hidden={currentView !== AppView.DATA}>
            <DataStudio
              data={data} headers={headers} activeFilters={activeFilters} setActiveFilters={setActiveFilters}
              onFileUpload={handleFileUpload} onProcessData={handleProcessData}
              onRemoveData={() => { resetData(); notify('Dataset purged', 'info'); }}
              onCleanData={(op) => { if (op === 'remove_duplicates') { handleProcessData('remove_duplicates', {}); } }}
              sessionId={sessionId}
              onUndo={handleUndo}
            />
          </div>
          <div className={currentView === AppView.VISUALIZE ? 'h-full' : 'hidden h-full'} aria-hidden={currentView !== AppView.VISUALIZE}>
            <Visualization
              data={data} isDarkMode={isDarkMode} headers={headers} config={{ ...vizConfig, columnFilters: activeFilters }}
              setConfig={setVizConfig} onAddToDashboard={handleAddToDashboard}
              activeFilters={activeFilters} setActiveFilters={setActiveFilters}
            />
          </div>
          <div className={currentView === AppView.INSIGHTS ? 'h-full' : 'hidden h-full'} aria-hidden={currentView !== AppView.INSIGHTS}>
            <AiInsights
              data={data} headers={headers} messages={chatMessages} setMessages={setChatMessages}
              onUpdateVisualization={(c) => { setVizConfig({ ...c, theme: 'default', aggregation: 'sum' }); setCurrentView(AppView.VISUALIZE); }}
              onCleanData={() => handleProcessData('remove_duplicates', {})}
              onAddToDashboard={handleAddToDashboard} sessionId={sessionId}
            />
          </div>
        </div>
      </main>
      <SettingsModal isOpen={isSettingsOpen} isDarkMode={isDarkMode} onToggleDarkMode={() => setIsDarkMode(!isDarkMode)} onClose={() => setIsSettingsOpen(false)} />
    </div>
  );
}

function App() {
  return (
    <NotificationProvider>
      <DataProvider>
        <AppContent />
      </DataProvider>
    </NotificationProvider>
  );
}

export default App;