import json
from typing import List, Dict, Any
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

class ReproducibilityService:
    """
    Service to generate standalone Python scripts replicating the tool's data cleaning logic.
    """

    def generate_script(self, report: List[Dict[str, Any]], original_filename: str = "data.csv") -> str:
        """
        Convert a reasoning report into a structured Pandas script.
        """
        script_parts = [
            'import pandas as pd',
            'import numpy as np',
            'from sklearn.preprocessing import StandardScaler',
            '',
            f'# Automated Data Engineering Script for {original_filename}',
            '# Generated by Flowmatics Intelligence Engine',
            '',
            f"df = pd.read_csv('{original_filename}')",
            'print(f"Original shape: {df.shape}")',
            ''
        ]

        for entry in report:
            action = entry.get("action")
            col = entry.get("column")
            cols = entry.get("columns")
            reason = entry.get("reason", "")

            script_parts.append(f"# {action.upper()}: {reason}")
            
            if action == "drop_columns":
                script_parts.append(f"df.drop(columns={cols}, inplace=True)")
            
            elif action == "impute":
                strategy = entry.get("strategy")
                if strategy == "mean":
                    script_parts.append(f"df['{col}'] = df['{col}'].fillna(df['{col}'].mean())")
                elif strategy == "median":
                    script_parts.append(f"df['{col}'] = df['{col}'].fillna(df['{col}'].median())")
                elif strategy == "mode":
                    script_parts.append(f"df['{col}'] = df['{col}'].fillna(df['{col}'].mode()[0])")
            
            elif action == "remove_duplicates":
                script_parts.append("df.drop_duplicates(inplace=True)")
            
            elif action == "outlier_clipping":
                script_parts.append(f"mean, std = df['{col}'].mean(), df['{col}'].std()")
                script_parts.append(f"df['{col}'] = df['{col}'].clip(lower=mean - 3*std, upper=mean + 3*std)")
            
            elif action == "standardize":
                script_parts.append(f"df['{col}'] = (df['{col}'] - df['{col}'].mean()) / df['{col}'].std()")
            elif action == "minmax_scale":
                script_parts.append(f"df['{col}'] = (df['{col}'] - df['{col}'].min()) / (df['{col}'].max() - df['{col}'].min())")
            elif action == "pca":
                n_components = entry.get("reduced_features", 2)
                script_parts.append("scaler = StandardScaler()")
                script_parts.append("numeric_df = df.select_dtypes(include=[np.number])")
                script_parts.append("scaled = scaler.fit_transform(numeric_df)")
                script_parts.append(f"pca = PCA(n_components={n_components})")
                script_parts.append("pca_data = pca.fit_transform(scaled)")
                script_parts.append("pca_cols = [f'pc_{i+1}' for i in range(pca_data.shape[1])]")
                script_parts.append("df_pca = pd.DataFrame(pca_data, columns=pca_cols, index=numeric_df.index)")
                script_parts.append("df = pd.concat([df.drop(columns=numeric_df.columns), df_pca], axis=1)")
            elif action == "extract_date":
                features = entry.get("features", [])
                for feat in features:
                    script_parts.append(f"df['{col}_{feat}'] = pd.to_datetime(df['{col}']).dt.{feat}")
            
            elif action == "onehot_encode":
                script_parts.append(f"df = pd.get_dummies(df, columns=['{col}'], prefix='{col}')")
            
            elif action == "label_encode":
                script_parts.append(f"df['{col}'] = df['{col}'].astype('category').cat.codes")

            script_parts.append("")

        script_parts.append('print(f"Final shape: {df.shape}")')
        script_parts.append('print("Processing complete.")')
        
        return "\n".join(script_parts)

reproducibility_service = ReproducibilityService()
